### ISSUE TITLE
Accidentally removed tray icon

### ISSUE THREAD

**Issue by Patneu** [dlech/Keebuntu#40]
Well, like it says above, I accidentally removed the KeePass2 applet and don't know how to get it back. I tried to add it like I would any other applet, but it doesn't appear in the list. Also tried to restart the computer and to reinstall KeePass2 as well as the plugin. Didn't work either.

Sorry if this is a dumb question, but I really couldn't find a hint on how to do it. (Or maybe I'm the first person dumb enough to remove it...)

I use Linux Mint 17.3 64-bit with Cinnamon and KeePass 2.33. If I can provide any more useful info, please let me know.

Thanks in advance for any help on this. =)

**Comment by dlech** [comment]
which plugin (package) are you using? which version?

There is no Cinnamon applet plugin, so I wouldn't expect it to be in the list. It is either an application indicator or a legacy GNOME tray icon depending on which package you installed.

**Comment by Patneu** [comment]
The KeePass "Plugins" menu says it's KeebuntuAppIndicator 0.4.6.0.

**Comment by dlech** [comment]
I'm not sure how you could remove it without uninstalling the plugin. Do you remember what you did to remove it?

**Comment by Patneu** [comment]
Yes, I right-clicked on it and chose "Dieses Applet entfernen" (should be something like "Remove this applet" in english). Before I did that, it worked like expected.

**Comment by dlech** [comment]
I did a quick search and I think you removed the "Indicator Applet". In other words, an applet that hosts application indicators. According to [this page](https://forums.linuxmint.com/viewtopic.php?f=90&t=61875) you can restore it by:

    So, on the panel right click -> Add to Panel... -> Indicator Applet and press Add

You could also try the [Classic Tray Icon](https://github.com/dlech/Keebuntu#classic-tray-icon) plugin instead of the [Application Indicator](https://github.com/dlech/Keebuntu#application-indicator). Some Cinnamon users prefer the classic because it has different behaviors for right and left click.

**Comment by Patneu** [comment]
Yes, thank you, that was the problem. =) In german the applet was called "Benachrichtigungsfeld" (thought I would leave that here for future german users with the same problem). Anyway, everything works like expected again, thanks again.^^
